### ISSUE TITLE
Error trying to use remote LAPI

### ISSUE THREAD

**Issue by pedromargarido** [crowdsecurity/home-assistant-addons#32]
I'm getting this errors:

```
time="22-02-2023 08:04:09" level=fatal msg="starting outputs error : authenticate watcher (1cad4328d7cc43d4aaec3d40863844aecqz2vR7KqdblDQOq): Post \"http://10.30.0.4:8080/v1/watchers/login\": could not get jwt token: Post \"http://10.30.0.4:8080/v1/watchers/login\": dial tcp 10.30.0.4:8080: i/o timeout"

s6-svscanctl: fatal: unable to control /var/run/s6/services: No such file or directory
```

My config:

```
acquisition: |
  ---
  source: journalctl
  journalctl_filter: 
    - "--directory=/var/log/journal/"
  labels:
    type: syslog
disable_lapi: true
remote_lapi_url: http://10.30.0.4:8080
agent_username: my_username
agent_password: my_password
collections:
  - crowdsecurity/home-assistant
parsers: []
scenarios: []
postoverflows: []
parsers_to_disable: []
scenarios_to_disable: []
disable_online_api: false
```

The username and password I got from the local_api_credentials.yaml file on the remote LAPI server.
